# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cardslib}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wael Nasreddine (TechnoGate)", "Malek Ben Othman (TechnoGate)", "Fatima El-Ouarrat (TechnoGate)", "Kaltouma Jbara (TechnoGate)"]
  s.date = %q{2011-01-15}
  s.description = %q{cardslib evaluates a hand of poker very fast}
  s.email = ["wael.nasreddine@technogate.fr", "malek.ben.othman@technogate.fr", "fatima.el.ouarrat@technogate.fr", "kaltouma.jbara@technogate.fr"]
  s.extensions = ["ext/cardslib_native/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".todo",
    "AUTHORS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "cardslib.gemspec",
    "ext/cardslib_native/cardslib_native.c",
    "ext/cardslib_native/cardslib_native.h",
    "ext/cardslib_native/extconf.rb",
    "ext/cardslib_native/includes/arrays.h",
    "ext/cardslib_native/includes/cards.c",
    "ext/cardslib_native/includes/cards.h",
    "ext/cardslib_native/includes/helper.c",
    "ext/cardslib_native/includes/helper.h",
    "ext/cardslib_native/includes/poker.c",
    "ext/cardslib_native/includes/poker.h",
    "features/features/cards_can_find_card.feature",
    "features/features/cards_can_identify_card.feature",
    "features/features/cards_can_identify_hand.feature",
    "features/features/deck.feature",
    "features/features/native_classes_and_modules.feature",
    "features/features/poker_can_eval_hand.feature",
    "features/features/poker_has_dealer.feature",
    "features/features/poker_has_levels.feature",
    "features/features/poker_has_player_turn.feature",
    "features/features/poker_has_players.feature",
    "features/features/poker_has_size.feature",
    "features/features/poker_has_type.feature",
    "features/features/poker_player_can_call.feature",
    "features/features/poker_player_can_fold.feature",
    "features/features/poker_player_can_raise.feature",
    "features/features/version.feature",
    "features/step_definitions/cardslib_steps.rb",
    "features/support/env.rb",
    "lib/cardslib.rb",
    "lib/cardslib/card.rb",
    "lib/cardslib/cards.rb",
    "lib/cardslib/native.rb",
    "lib/cardslib/poker.rb",
    "lib/cardslib/poker/caribbean_stud_poker.rb",
    "lib/cardslib/poker/common.rb",
    "lib/cardslib/poker/five_card_draw.rb",
    "lib/cardslib/poker/omaha.rb",
    "lib/cardslib/poker/seven_and_stud.rb",
    "lib/cardslib/poker/texas_holdem.rb",
    "lib/cardslib/version.rb",
    "spec/cardslib/card_spec.rb",
    "spec/cardslib/cards_spec.rb",
    "spec/cardslib/native_spec.rb",
    "spec/cardslib/poker_spec.rb",
    "spec/cardslib/version_spec.rb",
    "spec/spec_helper.rb",
    "tasks/bootstrap.rake",
    "tasks/c_extensions.rake",
    "tasks/cucumber.rake",
    "tasks/jeweler.rake",
    "tasks/rdoc.rake",
    "tasks/rspec.rake",
    "tasks/shortcuts.rake",
    "test/c/001_cards_001_find_card.c",
    "test/c/001_cards_002_identify_card.c",
    "test/c/001_cards_003_identify_hand.c",
    "test/c/002_poker_001_eval_5hand.c",
    "test/c/002_poker_002_eval_6hand.c",
    "test/c/002_poker_003_eval_7hand.c"
  ]
  s.homepage = %q{http://www.technogate.fr/projects/cardslib}
  s.licenses = ["GPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{cardslib evaluates a hand of poker very fast}
  s.test_files = [
    "spec/cardslib/card_spec.rb",
    "spec/cardslib/cards_spec.rb",
    "spec/cardslib/native_spec.rb",
    "spec/cardslib/poker_spec.rb",
    "spec/cardslib/version_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rake-compiler>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 1.5"])
      s.add_development_dependency(%q<rspec>, [">= 2.4.0"])
      s.add_development_dependency(%q<rake-tester>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<spork>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, ["> 0"])
      s.add_development_dependency(%q<rake-tasks>, ["> 0"])
      s.add_development_dependency(%q<rake-tester>, ["> 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.5"])
      s.add_dependency(%q<rspec>, [">= 2.4.0"])
      s.add_dependency(%q<rake-tester>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<spork>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, ["> 0"])
      s.add_dependency(%q<rake-tasks>, ["> 0"])
      s.add_dependency(%q<rake-tester>, ["> 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.5"])
    s.add_dependency(%q<rspec>, [">= 2.4.0"])
    s.add_dependency(%q<rake-tester>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<spork>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, ["> 0"])
    s.add_dependency(%q<rake-tasks>, ["> 0"])
    s.add_dependency(%q<rake-tester>, ["> 0"])
  end
end

